language: node_js
dist: trusty
node_js:
  - "10"
install:
  - npm i
script:
  - npm run build
branches:
  only:
    - master
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  local-dir: dist
  on:
    branch: master
