language: node_js
dist: trusty
node_js:
  - "10"
install:
  - npm i
script:
  - npm run build
  - chmod +x deploy.sh
  - ./deploy.sh
branches:
  only:
    - master
cache:
  directories:
    - node_modules
